### PR TITLE
Feat/whatsnextanimation2

### PR DESCRIPTION
**Pull request by gg119**
Reformated the section a little more

### CODE REVIEW

**Review by byluz — DISMISSED** [review]
okay

**Review by zkaramanlis — CHANGES_REQUESTED** [review]
Git Gud

**Review by Lhito — CHANGES_REQUESTED** [review]
extract the map into the slider component

**Review by Lhito — APPROVED** [review]
meh

**Review by zkaramanlis — APPROVED** [review]

**Pull request merged**
